name: MagicClock
main: MagicClock\Loader
version: 1.0.7
api: 1.0.0
author: iksaku
website: https://github.com/iksaku/MagicClock
softdepend:
 - EssentialsPE

permissions:
    magicclock:
        default: op
        description: "All the permissions to use the MagicClock"
        children:
            magicclock.exempt:
                default: op
                description: "Prevent to be hidden by the MagicClock"
            magicclock.canchat:
                default: op
                description: "Allow the player to chat if chat is disabled"
            magicclock.command:
                default: true
                description: "Allow the usage of the MagicClock command"
                children:
                    magicclock.command.get:
                        default: true
                        description: "Get the Magic Item!"